### ISSUE TITLE
fails to run on fresh install

### ISSUE THREAD

**Issue by cdaringe** [sinnerschrader/patternplate#110]
```
> octagon.react@0.1.0 start /Users/cdieringer/node/octagon.react
> patternplate start --open

⠹ Starting/Users/cdieringer/node/octagon.react/node_modules/patternplate/binary/patternplate.js:182
                throw error;
                ^

Error: Cannot find module 'patternplate-transform-browserify'
...
```

**Comment by cdaringe** [comment]
& `patternplate-transform-react`, `patternplate-transform-react-mount`, `patternplate-transform-react-to-markup`

**Comment by marionebl** [comment]
Thanks for reporting! `patternplate init` currently does not perform `npm install` / `yarn isntall`. Can you try and do that before executing `patternplate start` ?

**Comment by marionebl** [comment]
Released and published: 
https://github.com/sinnerschrader/patternplate/releases/tag/v1.0.7

```
❯ npm show patternplate version
1.0.7
```
