### ISSUE TITLE
Pass through files if no format is configured

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/patternplate#115]
Currently patternplate ignores any file that has no matching format defined in `configuration/patternplate-server/patterns.js`. Setting up a patternplate project thus requires a user to configure `formats` and `transforms` every single time. 

I think we should discuss if defining a set of pass-through formats/extensions that mirror the standardized web formats: `html`, `js` and `css`. 

## Example

```bash
# Given no configuration at /configuration/patternplate-server/patterns.js
patterns
|- button
|  |- pattern.json
|  |- demo.css # passed through
|  |- index.css
|  |- index.html # passed through
|  |- index.js # passed through
```

These pass-through formats would be delivered with (almost) no transformation. This concept works reasonably well for patterns without dependencies or source files with the need to import anything.

## Importing other pattern sources

Given resolving and linking currently is part of the concern transforms need to solve there is no obvious way to introduce patternplate-conforming import resolving to pass-through pattern sources. 

An idea on how to express imports in the pass-through formats. Please note: This disregards implications to current patternplate architecture.

```html
<!-- index.html -->
<link rel="import" href="pattern://dependency">
<div>
   <dependency/>
</div>
```

```css
/* index.css */
@import 'pattern://dependency';
```

```js
/* index.js */
const dependency = import 'pattern://dependency';
```

## Open questions
* Should we handle `imports` in passed through source files in any patternplate-specific way?
* If yes: When and how to resolve `imports` in passed through source files?
* If yes: How to handle errors in pattern resolving?
* If no: Whats our modularization story for pass-through formats?

**Comment by marionebl** [comment]
cc @KnisterPeter @Dangoo

**Comment by KnisterPeter** [comment]
What do you mean with `#used`?
I've add `pattern.json` to the files tree.

**Comment by marionebl** [comment]
@KnisterPeter: I changed `# used` to `# passed through` and added a comment about `pattern.formats` configuration being not there. Hope this makes things clearer.

**Comment by marionebl** [comment]
**Prototypical changes to patternplate-server**:
https://github.com/sinnerschrader/patternplate-server

**Demo project**: 
https://github.com/sinnerschrader/patternplate-getting-started/tree/feat/%23115-demo-passthrough-for-webformats

**Deployed demo**:
https://sinnerschrader.github.io/patternplate-getting-started/demos/passthrough-webformats/

**Comment by marionebl** [comment]
@KnisterPeter @LKuechler could you have a look at the prototype and give some feedback? More ideas for implementing pattern imports in the passthrough formats are welcome.

**Comment by KnisterPeter** [comment]
Something does not work with the button-row pattern

**Comment by KnisterPeter** [comment]
I don't like the html-import. The other formats could only be used if the pattern dependency resolver learns about uris/urls before.
There is no real good way to allow passthrough with modularization, because html/css/js does not support it on their own.

We should discuss this very seriously. Otherwise this will cost a lot for later versions.

**Comment by marionebl** [comment]
@KnisterPeter Concerning the html imports i think about emulating / wrapping the behavior you'd expect from browsers natively. This is still pretty rough in my head, but do you get the general idea? Perhaps something like https://github.com/felipeccastro/html-component shows the correct way to go about this.

**Comment by marionebl** [comment]
Obsolete as we will remove the transform chain
