### ISSUE TITLE
Quickstart issue with npm2

### ISSUE THREAD

**Issue by KnisterPeter** [sinnerschrader/patternplate#116]
Walking through the quick start guide when node4 (and therefore npm2) is the default in a new terminal will result in problems later on.

I think it would be great to have a shell script which does the first steps.
Maybe like this:
```shell
$ curl -o- -L https://raw.githubusercontent.com/sinnerschrader/patternplate/master/install.sh | bash
```

Inside this script the following steps should be executed:
```shell
#TODO: Check requirements (node >=4, npm >= 3)
npm install -g patternplate
patternplate init patternplate-project
cd patternplate-project
npm install
echo "Continue Quickstart with 'npm start -- --open'"
```

**Comment by marionebl** [comment]
I'd like to keep the source of truth for this in `package.json`. 

All `patternplate` cli commands could check if `process.version` and `npm -v` meet the requirements defined in `engines` and throw / warn if they don't. This would affect `patternplate init`, thus telling the user about the mismatch **before** the costly `npm install` in her project.

**Comment by KnisterPeter** [comment]
The first step `npm install patternplate` will already produce failures for the following steps and you could not check upfront if the user has npm >=3.

**Comment by marionebl** [comment]
Ok, obviously needs some testing. I'd aim at working with a plain `npm install` in any case.

**Comment by KnisterPeter** [comment]
To be fair: This results in issues if you do not install it globally. Did not try to install it globally with npm2.

**Comment by marionebl** [comment]
Guess this is obsolete by now
