### ISSUE TITLE
Light-Theme select box entries are not readable

### ISSUE THREAD

**Issue by KnisterPeter** [sinnerschrader/patternplate#117]
The entries of the options are not readable in the default theme.

![issue](https://cloud.githubusercontent.com/assets/327445/20029162/70a80372-a345-11e6-85b0-7d2299566caa.png)

**Comment by marionebl** [comment]
@Dangoo Do you find time for this / can you delegate further? Thanks!

**Comment by marionebl** [comment]
This problem is not visible on macOS. Could you add information about OS and browser @KnisterPeter?

Styling should be adapted here: 
https://github.com/sinnerschrader/patternplate-client/tree/master/source/assets/style/components/pattern

**Comment by Dangoo** [comment]
@marionebl I will have a look into this in about one week

**Comment by KnisterPeter** [comment]
My OS is debian and I'm using chrome.

**Comment by KnisterPeter** [comment]
This is caused by the declaration `color: transparent;` in the rule `.select__native`

**Comment by Dangoo** [comment]
Now reproduceable on FF maxOS too.

<img width="101" alt="bildschirmfoto 2017-02-17 um 10 24 28" src="https://cloud.githubusercontent.com/assets/1252204/23059823/53c91cca-f4fb-11e6-9862-fbef3e1a0fcb.png">
