### ISSUE TITLE
Change keyboard shortcuts to use ctrl+alt as modifier instead of just ctrl

### ISSUE THREAD

**Issue by KnisterPeter** [sinnerschrader/patternplate#118]
When running through the getting started guide inside a fresh patternplate instance, highlighting terminal commands and copy them via `ctrl+c` does not do what one would expect.

Currently `ctrl+c` opens the layer to modify the client redux state. The keybinding for this should be changed.

**Comment by marionebl** [comment]
This has not been raised yet because testing is performed on macOS systems. Thinking about the key bindings `ctrl` obviously is not safe to use as modifier key – any suggestion  what we could use instead?

**Comment by KnisterPeter** [comment]
What about `ctrl+shift+c` or `ctrl+alt+c`?

**Comment by marionebl** [comment]
Voting for `ctrl+alt` as general modifier. Any opinions @Dangoo ?

**Comment by KnisterPeter** [comment]
`ctrl+alt+c`

**Comment by marionebl** [comment]
Relevant sources to do functional changes:
https://github.com/sinnerschrader/patternplate-client/blob/master/source/assets/script/index.js#L30

Document here
https://github.com/sinnerschrader/patternplate-client/blob/3b74ff6c7ae800ed48f78c16d49a08588d383cd3/source/application/components/content/shortcuts.js#L15

**Comment by marionebl** [comment]
@Dangoo Do you find time for this / can you delegate further? Thanks!

**Comment by Dangoo** [comment]
@marionebl I will have a look into this in about one week.
