### ISSUE TITLE
Binaries are not executable

### ISSUE THREAD

**Issue by KnisterPeter** [sinnerschrader/patternplate#119]
The binaries in the git repo are not executable.
Normally this is not a problem since npm makes them executable, but if you use `npm link` or simple symlink yourself and watch the folder to rebuild on changes all binaries are recreated as non-executable on every change. This is quite anoying developer experience!  
Any reason to not make them executable in git?

**Comment by marionebl** [comment]
Go ahead!

**Comment by marionebl** [comment]
Reopen to remind me to release this.

**Comment by KnisterPeter** [comment]
It does not need to be released. It is mainly for contributor workflow. In any other case npm takes responsibility for making the binaries executable.
