### ISSUE TITLE
Dependencies of a pattern

### ISSUE THREAD

**Issue by KnisterPeter** [sinnerschrader/patternplate#129]
In 1.x you don't see the dependencies of your pattern anymore. Only dependents are shown.
Dependencies are equally important.

This are the entries in the pattern.json:
```json
{
	"name": "action-icon",
	"displayName": "Action Icon",
	"version": "0.11.0",
	"patterns": {
		"root": "globals/root",
		"demo-root": "globals/demo-root",
		"colors": "globals/colors",
		"grid": "globals/grid",
		"grid-cell": "globals/grid-cell",
		"grid-row": "globals/grid-row",
		"icon": "atoms/icon",
		"copy": "atoms/copy",
		"composed-icon": "molecules/composed-icon"
	}
}
```

This is the relations view:

![relations](https://cloud.githubusercontent.com/assets/327445/20555948/01f04272-b165-11e6-9d4c-a75f71e81807.png)

I would expect the dependencies in the relations view as well.

**Comment by marionebl** [comment]
@KnisterPeter Could you post an obfuscated screenshot of this?

This **should** work, as seen here: https://sinnerschrader.github.io/patternplate-getting-started/v2.0.0/pattern/molecules/button-row/?source=relations

Perhaps there is a JS issue? Could you have a look at the JS console for the affected pattern?

**Comment by marionebl** [comment]
This is very likely a regression introduced by https://github.com/sinnerschrader/patternplate-client/commit/1202f62a037a7a2473471d72fac17eadab78f27f

**Comment by marionebl** [comment]
@KnisterPeter Any chance you could pick this one up?

**Comment by KnisterPeter** [comment]
Not sure. I'll see if I will find some time.

**Comment by marionebl** [comment]
Fixed: https://github.com/sinnerschrader/patternplate-server/commit/3f4e194950c76c87db903c47d10c1b2b78cfed84
Released: https://github.com/sinnerschrader/patternplate-server/releases/tag/v1.0.16
