### ISSUE TITLE
Build fails for environments with different name

### ISSUE THREAD

**Issue by vegiepatch** [sinnerschrader/patternplate#13]
Adding a new environment for building another css file fails if name of folder and generated file are not the same.

Patternplate v 0.14.3

**Comment by marionebl** [comment]
Hey @vegiepatch, 
thanks for reporting!

could you provide some additional information? 
What would be especially of interest would be

* the failing environments configurations
* the used build task (`patternplate-console build` or `patternplate-console commonjs`)
* the stack trace of the error message if any.

**Comment by vegiepatch** [comment]
Hi Mario,

The build failed with npm run build. For the stack trace please see below
(verbose output attached).

Regards,
Simone

Mac OSX 10.10.5
node v4.0.0
npm 2.14.2


...
2016-01-27T11:20:54.608Z - info: [patternplate-server] [console:run]
Starting taskName "build"...
2016-01-27T11:20:54.609Z - warn: [patternplate-server] [console:run]
Starting taskName "build" without configuration...
2016-01-27T11:20:54.712Z - debug: [patternplate-server] [console:run]
Initializing pattern "@environments/index"
2016-01-27T11:20:54.976Z - debug: [patternplate-server] [console:run]
Reading pattern "@environments/index"
2016-01-27T11:21:28.106Z - debug: [patternplate-server] [console:run]
Initializing pattern "@environments/olb"
2016-01-27T11:21:28.268Z - debug: [patternplate-server] [console:run]
Reading pattern "@environments/olb"
2016-01-27T11:21:32.859Z - info: [patternplate-server] [console:run]
Writing "Style" for configuration "index" to
/Users/simjos/Documents/hal/website/ui.apps/src/main/prototype/build/build-v0.1.0-development-6acf027/index.css
...
/Users/simjos/Documents/hal/website/ui.apps/src/main/prototype/node_modules/patternplate/binary/patternplate-console.js:36
throw err;
^

TypeError: Cannot convert undefined or null to object
    at keys (native)
    at _loop
(/Users/simjos/Documents/hal/website/ui.apps/src/main/prototype/node_modules/patternplate/node_modules/patternplate-server/application/tasks/build/index.js:452:38)
    at
/Users/simjos/Documents/hal/website/ui.apps/src/main/prototype/node_modules/patternplate/node_modules/patternplate-server/application/tasks/build/index.js:487:5
    at next (native)
    at step
(/Users/simjos/Documents/hal/website/ui.apps/src/main/prototype/node_modules/patternplate/node_modules/patternplate-server/node_modules/babel-runtime/helpers/async-to-generator.js:14:30)
    at run
(/Users/simjos/Documents/hal/website/ui.apps/src/main/prototype/node_modules/patternplate/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:104:47)
    at
/Users/simjos/Documents/hal/website/ui.apps/src/main/prototype/node_modules/patternplate/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:115:28
    at flush
(/Users/simjos/Documents/hal/website/ui.apps/src/main/prototype/node_modules/patternplate/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run"
"patternplate-console" "build"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! hip-frontend@0.1.0 patternplate-console: `node --harmony
node_modules/patternplate/binary/patternplate-console.js "build"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hip-frontend@0.1.0 patternplate-console script 'node
--harmony node_modules/patternplate/binary/patternplate-console.js "build"'.
npm ERR! This is most likely a problem with the hip-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony
node_modules/patternplate/binary/patternplate-console.js "build"
npm ERR! You can get their info via:
npm ERR!     npm owner ls hip-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/simjos/Documents/hal/website/ui.apps/src/main/prototype/npm-debug.log

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! hip-frontend@0.1.0 build: `npm run patternplate-console build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hip-frontend@0.1.0 build script 'npm run
patternplate-console build'.
npm ERR! This is most likely a problem with the hip-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run patternplate-console build
npm ERR! You can get their info via:
npm ERR!     npm owner ls hip-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/simjos/Documents/hal/website/ui.apps/src/main/prototype/npm-debug.log

2016-01-27 12:03 GMT+01:00 Mario Nebl <notifications@github.com>:

> Hey @vegiepatch <https://github.com/vegiepatch>,
> thanks for reporting!
>
> could you provide some additional information?
> What would be especially of interest would be
>
>    - the failing environments configurations
>    - the used build task (patternplate-console build or patternplate-console
>    commonjs)
>    - the stack trace of the error message if any.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinnerschrader/patternplate/issues/13#issuecomment-175560467>
> .
>



-- 
Simone Joswig, Technical Director

simone.joswig@sinnerschrader.com
T  +49 40 398855 620
M +49 152 22711147

SinnerSchrader Deutschland GmbH | SinnerSchrader Group
Völckersstraße 38, 22765 Hamburg, Germany

Amtsgericht Hamburg HRB-Nr. 63663
Geschäftsführer: Matthias Schrader (Sprecher),
Jürgen Alker, Dr. Axel Averdung, Holger Blank,
Thomas Dyckhoff, Dr. Lars Finke, Martin Gassner

Büros: Hamburg, Frankfurt a. M., München, Prag

http://www.sinnerschrader.com | NEXT AGENCY

**Comment by marionebl** [comment]
Should be solved with patternplate@v0.15.13 and up.
