### ISSUE TITLE
Can't switch theme when pattern is selected

### ISSUE THREAD

**Issue by MartinHelmut** [sinnerschrader/patternplate#130]
**PatternPlate Version:** 1.0.10
**Tested in:** Chrome 54, Firefox 49, Safari 10

The theme switch is only possible on navigation root level, e.g. requesting the dark theme style: `http://localhost:1337/style/dark.css`.

After selecting an pattern (e.g. `http://localhost:1337/pattern/my-cool-pattern/`) and activating the theme switch, the wrong resource is requested: `http://localhost:1337/pattern/my-cool-pattern/style/dark.css`.

Also the following error is shown in console:

```shell
error:  Error unknown file: Cannot read property 'type' of null
```

**Comment by marionebl** [comment]
Thanks for reporting! Confirmed using the static build of [patternplate-getting-started](https://github.com/sinnerschrader/patternplate-getting-started):

**Works**: [light](https://sinnerschrader.github.io/patternplate-getting-started/v2.0.0/?theme=light) | [dark](https://sinnerschrader.github.io/patternplate-getting-started/v2.0.0/?theme=dark)
**Fails**: [light](https://sinnerschrader.github.io/patternplate-getting-started/v2.0.0/pattern/atoms/button/?theme=light) | [dark](https://sinnerschrader.github.io/patternplate-getting-started/v2.0.0/pattern/atoms/button/?theme=dark)

This is an issue with `createStyles` in `components/application/index.js` ([source](https://github.com/sinnerschrader/patternplate-client/blob/b8206349f67f49e9cde6c247aa4f34698bac7c53/source/application/components/application/index.js#L129)) not receiving a proper base value to determine the stylehsheet url.

**Comment by MartinHelmut** [comment]
Looks like a good bug to contribute to for me :D I will add a PR for this tomorrow.

**Comment by marionebl** [comment]
Theme switching will not make it into `2.0`, closing.
