### ISSUE TITLE
Feature request: build in snapshot testing for patterns

### ISSUE THREAD

**Issue by KnisterPeter** [sinnerschrader/patternplate#133]
With the latest [Jest update](http://facebook.github.io/jest/blog/2016/10/03/jest-16.html) it is possible to integrate jest/react snapshot testing in other tools like described [here](https://voice.kadira.io/snapshot-testing-in-react-storybook-43b3b71cec4f#.3oqszx44o).

It would be awesome to have testing for patterns as well.

**Comment by marionebl** [comment]
Obsolete as patternplate will move towards a dev/design tool without own transform chain.
