### ISSUE TITLE
Reloading folder views yields 403 pages on nginx

### ISSUE THREAD

**Issue by dipe** [sinnerschrader/patternplate#134]
**Actual**

When reloading a folder view via `ctrl+r` a 403 page is shown

**Expected**

The same folder view is produced

**Comment by KnisterPeter** [comment]
@marionebl could you confirm this behaviour?

**Comment by marionebl** [comment]
Confirmed for patternplate 1.0 and up

**Comment by marionebl** [comment]
related to #132

**Comment by marionebl** [comment]
@dipe Upgrading to patternplate 1.1.1 should fix the issue
