### ISSUE TITLE
Error on importing less

### ISSUE THREAD

**Issue by SaraVieira** [sinnerschrader/patternplate#135]
Hello there !

When I try to run patternplate and use resolve-includes to resolve includes in my less files before turning them into CSS I get : Error unknown file: Cannot read property 'patterns' of undefined.

This is my buttons/pattern.json 

```
{
  "name": "button",
  "displayName": "Button",
  "version": "1.0.0",
  "patterns": {
    "variables": "config/variables"
  }
}
```

**Comment by KnisterPeter** [comment]
Can you please add a few more information here?
It would be great to see `config/variables` and your `patternplate-transform-less` configuration.

**Comment by SaraVieira** [comment]
Sure @KnisterPeter 

This is my file structure, I'm trying to get the variables from a file outside of the patterns folder. This is my folder structure:
├── less
└── config
└─── variables.less
├── patterns
└── buttons
└─── pattern.json
└─── index.html
└─── index.less

This is my config:

```
module.exports = {
	'less': {
		inFormat: 'less',
		outFormat: 'css',
		plugins: {},
		opts: {}
	},
  "resolve-includes": {
    "resolve": "../../less/%(patternId)s/%(name)s.less"
  }
};
```

Is this even possible ?
Anything else just ask

**Comment by KnisterPeter** [comment]
I'm not sure if it is possible. It would be better to create a pattern named `vars` and place your variables in that pattern. This pattern could then be declared as dependency to every requiring pattern.

@marionebl what do you think?

**Comment by KnisterPeter** [comment]
Opened followup issue to improve documentation #136

**Comment by SaraVieira** [comment]
Even when  try that approach and create a new pattern for the configs I get the same error: Error unknown file: Cannot read property 'patterns' of undefined

**Comment by SaraVieira** [comment]
Yes , If I do it like that it works fine , I'll redesign the folder structure.
Is there anyway to have a pattern that does not appear on the menu ?

I'll have a look at the documentation

**Comment by KnisterPeter** [comment]
You could add the following to the `pattern.json` of that pattern:

```
{
    ...
    "options": {
        "hidden": true
    }
}
```

**Comment by SaraVieira** [comment]
That works great ! Thanks :)

**Comment by KnisterPeter** [comment]
Your welcome
