### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by SaraVieira** [sinnerschrader/patternplate#137]
I'm trying to add patternplate in a build and I wanted it to run in :8080, is it possible to change the port it runs ?

**Comment by KnisterPeter** [comment]
Just create a `configuration/server.js` and override [these](https://github.com/sinnerschrader/patternplate-server/blob/master/source/configuration/server.js) settings in there.

**Comment by SaraVieira** [comment]
I managed to do that with the CLI as well, now I wanted to publish this in a QA environment and it needs to listen on '/ui' instead of '/', is this also possible ?

Thank you

**Comment by KnisterPeter** [comment]
I think this is currently not possible. You could do so by using a reverse-proxy (e.g. apache, nginx or some custom node-server) in front of the QA environment.

**Comment by SaraVieira** [comment]
I can't touch the server configuration :/

Do you know any other way to do this ?

**Comment by KnisterPeter** [comment]
Sorry no, I think there is no other way around it.
You may be able to write a node programm and start patternplate from that. If you create your own express server in there and delegate the requests to patternplate then you have your own reverse-proxy. But it sounds very much like overkill.

Sorry.

**Comment by SaraVieira** [comment]
I even tried to fork patternplate server and changed the routes.js but that didn't seem to work.  So I'll have to follow that ideia and create a simple  node server 

Thanks

**Comment by SaraVieira** [comment]
So I forked the patternplate-client and I am almost there , all the files are served in '/ui' the only thing that is not working is what is served from the api , the source code and the json basically. DO you know any way around this ?

**Comment by KnisterPeter** [comment]
You need to fork the server as well for that.

**Comment by SaraVieira** [comment]
And do you know where I need to make the changes in the server?

**Comment by KnisterPeter** [comment]
Sorry, not just a single clue to give. I'm not that deep into it and I'm not sure about side effects.

**Comment by SaraVieira** [comment]
No problem,  thank you for your help so far. 

@sinnerschrader do you think you could help me with this?

**Comment by KnisterPeter** [comment]
Hej @SaraVieira, @marionebl is on vacation right now. Sorry for that.

**Comment by SaraVieira** [comment]
hey @KnisterPeter np :)

I was able to change that but when I deploy I get a piping error :(

**Comment by SaraVieira** [comment]
Locally it works great

**Comment by KnisterPeter** [comment]
@SaraVieira what do you mean by piping error? Do you have a stack trace? Or something I can help with?

**Comment by SaraVieira** [comment]
![screen shot 2017-02-03 at 15 12 37](https://cloud.githubusercontent.com/assets/1051509/22596317/f6e88028-ea22-11e6-9c6f-1fa91b855be3.png)

If this is not sufficient I can ask server permission

**Comment by KnisterPeter** [comment]
There should be a relevant server side error. The clients says 500 which normaly means it is a server error.

**Comment by SaraVieira** [comment]
I know it's a server error , I need to wait for someone who can get inside the machine and I will try to get the server log and I will get back to you on monday


Thank you

**Comment by SaraVieira** [comment]
It was a splitter problem in our side.
Thank you so much @KnisterPeter  for your help its working great on the QA server now 👍

**Comment by KnisterPeter** [comment]
I'm glad. Your welcome :smile:

**Comment by KnisterPeter** [comment]
If you like to you can publish your changes for a pull request.
I say we need to make it configurable to include it in patternplate, but we (or you) could do so.

**Comment by SaraVieira** [comment]
@KnisterPeter when I have the time I will configure the changes better because right now they are hard coded and I will create a pull request so that people can configure the path in the CLI

Is there any way I can load a static svg file ?
I'm trying to load an svg sprite

**Comment by KnisterPeter** [comment]
I don't think so. You need to host it somewhere. There is no static file server in patternplate and it would probably out of scope.

**Comment by SaraVieira** [comment]
I'm just asking because sometimes you do need something like an image in a pattern library

**Comment by KnisterPeter** [comment]
You could use a placeholder service like this https://image.sinnerschrader.io/Your+Image/aaa/844/800x600/image.png or some kittens. :smile:

**Comment by SaraVieira** [comment]
Kittens are never a bad idea and something that I will always approve of 😄 

The problem is i'm trying to load an svg sprite that is dynamically created , so i'm going to try to make some tweaks to the server to see if I can make it serve a static folder with images or something. Would this be something you guys would like included ? Should I later create a pull request for this when done ?

**Comment by Dangoo** [comment]
@KnisterPeter once we had a `/static` folder on the same level as for the `/patterns` which became available via `<domain.io>/api/static`. Is this outdated by now?

@SaraVieira What exactly do you mean by "dynamically created"? A taskrunner building and deploying the sprite to a specific folder oder created from patterns of the patternplate?

**Comment by KnisterPeter** [comment]
@Dangoo I didn't know this. Maybe it will work.

@SaraVieira I would not think that static files should be included in your pull requests. At least split the two features into two requests.

**Comment by SaraVieira** [comment]
I dont mean include the static files in the pull request but instead create
a pull requests that changes the server in order to also serve am assets
folder for the pattern if needed

**Comment by KnisterPeter** [comment]
Currently I'm not sure if we need this feature. And maybe it is already implemented. See the comment above from @Dangoo

**Comment by SaraVieira** [comment]
@Dangoo @KnisterPeter It was already implemented in the static folder like he said and I did manage to get it working: [http://imgur.com/a/pZpiA](http://imgur.com/a/pZpiA).

Thank you so much for both your help and any help you need here in patternplate just let me know and I would love to help this project

**Comment by KnisterPeter** [comment]
You're welcome. Glad that we could help you. :rocket: 
If you like to, have a look at the current issues. The 'good for beginners' may be a good starting point.
