### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by Xiphe** [sinnerschrader/patternplate#14]
Hello lovely patternplate people :)

@KarstenBuckstegge and @meandmax told me about this project and since i'm currently working on a ui-library for @Jimdo i'm really curious on your approach on this.

We're currently on the status of having a central place to write the css for our patterns which can be consumed as a bower component along with a sass file containing constants like colors and animations.

Right now we use the pattern markup as the 'API', so that a developer has to copy-paste a html snippet that will then pickup the styles from our library. True north would be to have that behind a more abstract API and from what i heard, that is kind of the direction you're going here - but from looking at the source i can't really tell how and if this is the case ;)

Since it seems as if you're going with an Open Source approach i wonder if (given we're going into the same direction) there are things we could join forces on.

So if you're interested, i'd love to share a few beers with you and talk about this stuff.

Feel free to also [drop me an E-Mail](mailto:hannes.diercks@jimdo.com)

**Comment by marionebl** [comment]
Hey @Xiphe,

sorry for the delay (pretty deep into the woods getting [this](https://github.com/sinnerschrader/patternplate-server/tree/feature/faster-yet-no-pattern-cache) released) and thanks for reaching out!

What we strive to build is a system where everything, the markup included, is part of defined APIs and a completely transparent dependency tree. Currently we achieve this by relying on React/JSX to define the markup and its possible permutations for each component. Personally I consider this the central perk of using patternplate, as I grew tired of copy-pasting markup some day last year :trollface:

As you see documentation currently is non-existing, but we are well underway on changing this: https://github.com/sinnerschrader/patternplate-minutes

I'm pretty sure we could benefit hugely by joining forces. What about a meeting :beers:  at the beginning of next week?

**Comment by marionebl** [comment]
cc @KnisterPeter @Dangoo

**Comment by Xiphe** [comment]
Great! Since i'm quiet busy the next weeks i've sent you a doodle link with my free times to the public E-Mail-Adress from your Github repo. I'm really looking forward to this ;)

**Comment by KarstenBuckstegge** [comment]
\o/ Please let me know when this meeting is happening as well. I would love to join in. :)

**Comment by Xiphe** [comment]
karsten, i've sent you the doodle link. If anybody else wants to join, feel free to drop me a line. Though i think it would be most productive if we keep the round at about 3-6 people

**Comment by KnisterPeter** [comment]
I would love to attend as well

**Comment by Xiphe** [comment]
@KnisterPeter please ask @marionebl for the doodle-link or [send me an E-Mail](mailto:hannes.diercks@jimdo.com)

**Comment by Xiphe** [comment]
Sorry guys, i missed that i'll not be in Hamburg on the 23.02. i added a few more options.

**Comment by Xiphe** [comment]
Or should we "under four eyes" @marionebl or @Dangoo?
Maybe that would be enough to get to know each other and check if the directions we're heading at actually match. Later on we could then come together with a bigger group and come up with an action plan or so...

**Comment by marionebl** [comment]
Hey @Xiphe, I'd be fine with a smaller meeting to kick off the bigger one. Let's meet up on the 17th then, location to your choosing.

**Comment by Dangoo** [comment]
Hey @Xiphe and @marionebl, sadly can't make it the 17th…
Will grab information afterwards ;)

**Comment by Xiphe** [comment]
Ok @marionebl i'd like to go to [Altes Mädchen](http://de.altes-maedchen.com/) is that fine for you? Or s.th. closer like [Titanic](https://www.tripadvisor.de/Restaurant_Review-g187331-d1038823-Reviews-Titanic-Hamburg.html)?

**Comment by marionebl** [comment]
Altes Mädchen is fine, see you there.

**Comment by Xiphe** [comment]
:+1:

**Comment by Xiphe** [comment]
So @marionebl @KarstenBuckstegge and me met yesterday evening.

We want to try to build a JSX to anything parser that could play well together with the upcoming concept of environments in the pattern plate. Mario will split existing logic into a new repository in order to have a single purpose tool we can iterate on.

We'd like to dig deeper and see if and why (not) Jimdo could build it's ui-library with patternplate. But that seems to need a bit more time and hands-on experience. So we'll schedule a new meeting at Jimdo -> #20
