### ISSUE TITLE
Feature Request: Preserving structure for search results

### ISSUE THREAD

**Issue by Dangoo** [sinnerschrader/patternplate#140]
Proposal for preserving for preserving the navigation structure for search results.

*Current state:*
Typing into search field shows results sorted alphabetically

*Proposed behaviour:*
Typing into search field shows results grouped/marked in their folders. The folders may preserve their order according to configuration and the patterns inside become ordered alphabetically.
The style of the Folder grouping may vary from default menu styling.

I'd like to here some other thoughts on this topic. So please vote this post up or down if you agree/disagree with this proposal.

/cc @marionebl @KnisterPeter @LKuechler

**Comment by marionebl** [comment]
@Dangoo Could you expand on what we'd achieve with changing the current behaviour? E.g. what are the UX problems we have now and how are they solved with this?

**Comment by marionebl** [comment]
Search will be performed in the search overlay as of `2.0` and always show a flat list.
