### ISSUE TITLE
Custom pattern path

### ISSUE THREAD

**Issue by leonidax** [sinnerschrader/patternplate#147]
Right now patternplate forces me to have patterns subdirectory as my root directory but I'm trying to use patternplate with an already existing project where changing the structure would be hard, maybe I missed something an there is a way to indicate to patternplate to use other directory as root directory.

**Comment by marionebl** [comment]
Hey @leonidax - the `patterns` directory is not configurable at the moment, sorry.

**Comment by leonidax** [comment]
Hi @marionebl, just as a suggestion, maybe you should not close this kind of issues and label them as a feature request, unless that you really don't want to have this kind of feature at all.

**Comment by marionebl** [comment]
@leonidax: You are totally right.

**Comment by marionebl** [comment]
Users will be able to configure the position of pattern sources freely in `2.0.0`
