### ISSUE TITLE
Demos don't work in v2.0.0.-4

### ISSUE THREAD

**Issue by pixelass** [sinnerschrader/patternplate#155]
## Versions

node: node/8.9.1   
npm: 5.5.1  
Patternplate: 2.0.0-4  

## Issue description

Patternplate seems to have an issue when it is started before the lib has been fully built. 
This can be experienced by running the examples. `stmux` will not wait for the initial build. 

If this issue is due to the build/watch logic and cannot be changed we should mention it in the Readme.md and adjust the examples.

## Steps to reproduce

Depends on the transpile/build time. The webpack-less example seems to constantly have this issue so I suggest to reproduce it here: https://github.com/sinnerschrader/patternplate/tree/chore/lernaify/examples/webpack-react-less

## Expected behavior 

Patterplate displays demos even when lib does not exist before startup

## Actual behavior

Patterplate demos have an error when the initial build process takes too long.  
All directories that are not fully available before patternplate is started have an issue:

## Log (example)

```shell
Cannot use 'in' operator to search for 'src/button/button.demo.js' in undefined
```

**Comment by marionebl** [comment]
Please retest with `2.0.0-6`, this should work now.

**Comment by pixelass** [comment]
sorry for the late reply... tested and confirmed.
