### ISSUE TITLE
Tagging System

### ISSUE THREAD

**Issue by LKuechler** [sinnerschrader/patternplate#17]
Ability to add Tags for each Pattern.
This Feature can then be used in alternative display methods for the pattern structure. #18

Ticket based on [patternplate vision meeting](./vision/patternplate-vision-16-01-21.md)

**Comment by marionebl** [comment]
This is implemented as of [patternplate-client@v0.14.5](https://github.com/sinnerschrader/patternplate-client/releases/tag/v0.14.5)
