### ISSUE TITLE
Validate dependency structure

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/patternplate#24]
A way to configure validation for dependency structures between pattern folder could be hugely beneficial, especially for projects with large dependency trees. 

This should allow:
* Applying arbitrary number of rules to arbitrary paths in `patterns` via positive and negative glob patterns
* Configure the severity of rules, supporting `['warn', 'error']`
* Configuring arbitrary numbers allowed dependency paths via positive and negative glob patterns

The configuration could take the form of
```js
// patternplate-server/configuration/patterns.js
module.exports = {
  dependencies: {
    rules: [
      {
        apply: ["atoms/**/*"],
        depend: [] // no depending allowed,
        severity: "error"
      },
      {
        apply: ["molecules/**/*"],
        depend: ["atoms/**/*"],
        severity: "warn"
      },
      {
        apply: ["organisms/**/*"],
        depend: ["atoms/**/*", "molecules/**/*"],
        severity: "error"
      },
      {
        apply: ["templates/**/*"],
        depend: ["atoms/**/*", "molecules/**/*", "organisms/**/*"],
        severity: "error"
      },
      {
        apply: ["pages/**/*"],
        depend: ["templates/**/*"],
        severity: "error"
      }
    ]
  }
}
```

**Comment by marionebl** [comment]
cc @KnisterPeter @Dangoo

**Comment by KnisterPeter** [comment]
What is the severity good for?

**Comment by Dangoo** [comment]
For experienced user it could be helpfull and even speed up the dependency resolving (+1).

But on the other hand side it add another layer of complexity to understand for newcomers…

**Comment by marionebl** [comment]
@KnisterPeter The severity should allow for control if breaking a given rules yields warning or errors, something I'd consider a given concerning the configurability of linting functionality.

**Comment by marionebl** [comment]
@Dangoo: By default patternplate wouldn't define any dependency structure rules, this stays strictly optional. As a plus I'd devise an easy way to generate an UML description (like [this](https://github.com/sinnerschrader/patternplate#development)) of the allowed dependency relations. Does this address your concern?

**Comment by KnisterPeter** [comment]
+1 from me

**Comment by felabr** [comment]
Can we tell apart dependencies used in patterns from dependencies used only in demos? I wouldn't want the demo ones to be considered here.
