### ISSUE TITLE
Feat: Brand (multi color) mode

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/patternplate#27]
_From @Dangoo on February 24, 2016 17:28_

Patternplate can display patterns designed for one single brand/client.
But sometimes it is necessary to build a white label solution and display some occurrences.
What about adding a switch to enable testing of different versions of the patterns?

_Copied from original issue: sinnerschrader/patternplate-client#165_

**Comment by marionebl** [comment]
Basically `patternplate-server` already supports this via the environments functionality (documentation pending). 

We could devise a simple interface (GET-parameters?) for the`patternplate-client` to force a given environment on the patterns it requests from `patternplate-server`. 

The bulk of the work for this would have to be done in [routes/pattern.js](https://github.com/sinnerschrader/patternplate-server/blob/master/source/application/routes/pattern.js).

I'm not sure where to place this in the frontend, any suggestions?

/cc @levito @KnisterPeter @felabr

**Comment by marionebl** [comment]
_From @Dangoo on February 24, 2016 17:37_

I'd suggest either globally on the place of the former download select or directly in the head of each pattern (Toolbar planed for 1.0 required)

**Comment by marionebl** [comment]
I'm strongly in favor of locating this at individual patterns as environment config essentially applies to each pattern individually.

**Comment by marionebl** [comment]
_From @KnisterPeter on February 24, 2016 18:38_

I would favor it in the toolbar as well

**Comment by martinemmert** [comment]
https://github.com/sinnerschrader/patternplate-server/pull/60
