### ISSUE TITLE
Allow react stateless functional components

### ISSUE THREAD

**Issue by chatzipan** [sinnerschrader/patternplate#47]
At the moment only components that extend the React.Component class are allowed. It would be nice if one could use functional components as well.

**Comment by marionebl** [comment]
This is in the works at https://github.com/sinnerschrader/patternplate-transform-react/pull/1

**Comment by marionebl** [comment]
This is now possible via https://github.com/sinnerschrader/patternplate-transform-react-to-markup/releases/tag/v0.3.1
