### ISSUE TITLE
css file extension for commonjs export

### ISSUE THREAD

**Issue by Dangoo** [sinnerschrader/patternplate#50]
Exported CSS files in commonjs-bundle have .less extensions instead of .css extensions.

**is:** .less 
**should:** .css

**Comment by marionebl** [comment]
Thanks for your report, I'll have a look asap

**Comment by marionebl** [comment]
This is support via the `transforms.resolve-includes` config:

```js
// configuration/patternplate-server/build.js
module.exports = {
	commonjs: {
		transforms: {
			'resolve-includes': {
				outFormat: 'css'
			}
		}
	}
};

```
