### ISSUE TITLE
Rewrite static ressources paths

### ISSUE THREAD

**Issue by Dangoo** [sinnerschrader/patternplate#51]
In patternplate static resources are located in `./static/…`and can be accessed via `/api/static/…`.
In the commonjs export the resource url does not get resolved to point to `/static/…` instead of `/api/static/…`. So a module-resolver like webpack (with file-loader) cannot resolve/rewrite the paths to the static resources.

**Comment by marionebl** [comment]
I removed the bug label, as I think this a missing feature at the very most. I'd like to discuss if this is actually needed or should be solved in user-land by either:

* Using variables in less, sass, postcss to make static paths etc. configurable for the consumer
* A postbuild-step dealing with rewriting urls

A interesting aspect of this could be the question of exposing the contents of `./static` better.

cc @KnisterPeter

**Comment by marionebl** [comment]
Any further input on this @Dangoo?

**Comment by Dangoo** [comment]
For any environment with CSS preprocessors which are capable of variable replacement this should not be a problem. I have no better solution for handling that on the tool side independent from the styling processor…

**Comment by marionebl** [comment]
I am closing this for now. We can pick up the discussion on this when we think about pulling statics into patterns instead of the static folder.
