### ISSUE TITLE
patternplate-transform-resolve-includes does not add npm dependencies anymore

### ISSUE THREAD

**Issue by timbru31** [sinnerschrader/patternplate#54]
The commit https://github.com/sinnerschrader/patternplate-transform-resolve-includes/commit/d5b02d2020927299aae7f757755df0ec57cd5f3c#diff-c60c67bd505d9618ebf77a7f130903d0L35 (line 35) removed the 
`file.meta.dependencies.push(packageName);`

This results in the bug that dependencies in e.g. less files are not respected anymore and are lost.

**Comment by marionebl** [comment]
https://github.com/sinnerschrader/patternplate-transform-resolve-includes/releases/tag/v0.1.4
