### ISSUE TITLE
build-commonjs task on windows systems

### ISSUE THREAD

**Issue by seriouscircus** [sinnerschrader/patternplate#61]
On Mac the build-commonjs command runs faster because only an incremental build is performed. On windows always the complete build is executed. Is there an easy fix for this?

**Comment by marionebl** [comment]
@seriouscircus: Could you provide more details about your OS, then I'll look into it.

**Comment by seriouscircus** [comment]
perfect.
Windows 10, Node 4.4.0, using Windows Command Prompt or Git Bash
