### ISSUE TITLE
Links in particle documentation don't work

### ISSUE THREAD

**Issue by Tschoatscho** [sinnerschrader/patternplate#7]
Links in "index.md" (Tab "Documentation") don't work if content of tab "Markup" is not visible.
Obviously the latter catches mouse events even when hidden.
When tab "Markup" is visible tab "Documentation" is pushed down within the page and all links work. Otherwise only links in "Documentation" which are positioned below the height of "Markup" content respond to clicks.

**Comment by opatut** [comment]
Thank you for your contribution. However, this issue has already been reported in sinnerschrader/patternplate-client#3. Please follow progress there to stay updated.

Generally speaking, this is a frontend-only problem, so it's scope is the patternplate-client project.
