### ISSUE TITLE
Node v6.2.0

### ISSUE THREAD

**Issue by LKuechler** [sinnerschrader/patternplate#71]
When using the current stable node version no pattern can be viewed.
Opening a pattern throws this error:

> Error in "atoms/button" during transform "browserify" of "/Users/laskue/projects/test/patterns/atoms/button/index.js": Path must be a string. Received { buffer: '(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module \'"+o+"\'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){\n"use strict";\n\nconsole.log("test");\n\n},{}]},{},[1])\n\n;\n//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5vZGVfbW9kdWxlcy9wYXR0ZXJucGxhdGUtdHJhbnNmb3JtLWJyb3dzZXJpZnkvbm9kZV9tb2R1bGVzL2Jyb3dzZXItcGFjay9fcHJlbHVkZS5qcyIsIi9Vc2Vycy9sYXNrdWUvcHJvamVjdHMvdG9vbHMvdXgtdG9vbGtpdC9wYXR0ZXJucy9hdG9tcy9idXR0b24vaW5kZXguanMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7OztBQ0FBLE9BQU8sQ0FBQyxHQUFHLENBQUMsTUFBTSxDQUFDLENBQUEiLCJmaWxlIjoiL1VzZXJzL2xhc2t1ZS9wcm9qZWN0cy90b29scy91eC10b29sa2l0L3BhdHRlcm5zL2F0b21zL2J1dHRvbi9pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbIihmdW5jdGlvbiBlKHQsbixyKXtmdW5jdGlvbiBzKG8sdSl7aWYoIW5bb10pe2lmKCF0W29dKXt2YXIgYT10eXBlb2YgcmVxdWlyZT09XCJmdW5jdGlvblwiJiZyZXF1aXJlO2lmKCF1JiZhKXJldHVybiBhKG8sITApO2lmKGkpcmV0dXJuIGkobywhMCk7dmFyIGY9bmV3IEVycm9yKFwiQ2Fubm90IGZpbmQgbW9kdWxlICdcIitvK1wiJ1wiKTt0aHJvdyBmLmNvZGU9XCJNT0RVTEVfTk9UX0ZPVU5EXCIsZn12YXIgbD1uW29dPXtleHBvcnRzOnt9fTt0W29dWzBdLmNhbGwobC5leHBvcnRzLGZ1bmN0aW9uKGUpe3ZhciBuPXRbb11bMV1bZV07cmV0dXJuIHMobj9uOmUpfSxsLGwuZXhwb3J0cyxlLHQsbixyKX1yZXR1cm4gbltvXS5leHBvcnRzfXZhciBpPXR5cGVvZiByZXF1aXJlPT1cImZ1bmN0aW9uXCImJnJlcXVpcmU7Zm9yKHZhciBvPTA7bzxyLmxlbmd0aDtvKyspcyhyW29dKTtyZXR1cm4gc30pIiwiY29uc29sZS5sb2coXCJ0ZXN0XCIpXG4iXX0=', source: <Buffer 63 6f 6e 73 6f 6c 65 2e 6c 6f 67 28 22 74 65 73 74 22 29 0a>, name: 'index.js', basename: 'index', ext: '.js', format: 'js', fs: Stats { node: { dev: 16777220, mode: 33188, nlink: 1, uid: 501, gid: 20, rdev: 0, blksize: 4096, ino: 73768542, size: 20, blocks: 8, atime: 2016-05-25T14:24:02.000Z, mtime: 2015-12-22T21:59:58.000Z, ctime: 2015-12-22T21:59:58.000Z, birthtime: 2015-12-22T21:53:08.000Z }, size: 20 }, path: '/Users/laskue/projects/test/patterns/atoms/button/index.js', pattern: Pattern { files: { 'index.js': [Circular], 'index.jsx': [Object] }, config: { parents: [], patterns: [Object], transforms: [Object], log: [Object], name: 'index', version: '0.1.0', applyTo: [Object], include: [Object], excludes: [], priority: 0, environment: {}, environments: [] }, manifest: { version: '0.1.0', build: true, display: true, patterns: [Object], availableEnvironments: [], demoEnvironments: [], name: 'button', displayName: 'Button', dependentPatterns: {} }, dependencies: { Pattern: [Object] }, results: {}, mtime: Invalid Date, filters: { environments: [], inFormats: [], outFormats: [] }, log: LogQueue { fill: [Function] }, cache: PatternCache { config: [Object] }, id: 'atoms/button', base: '/Users/laskue/projects/test/patterns', transforms: { markdown: [Function], react: [Function], 'react-mount': [Function], 'react-to-markup': [Function: renderReactComponent], babel: [Function: babelTransform], browserify: [Function], uglify: [Function: uglifyTransform], less: [Function: lessTransform], 'resolve-includes': [Function], 'resolve-imports': [Function: rewriteImportsTransform] }, path: '/Users/laskue/projects/test/patterns/atoms/button', environments: { index: [Object] }, isEnvironment: false, fs: { list: [Function: bound ], stat: [Function: bound ], exists: [Function: bound ], read: [Function] }, outFormats: [ [Object], [Object] ], inFormats: [ 'js', 'less', 'css', 'html', 'jsx', 'md' ] }, meta: { dependencies: [], devDependencies: [] }, dependencies: { Pattern: { buffer: <Buffer 63 6f 6e 73 6f 6c 65 2e 6c 6f 67 28 22 74 65 73 74 22 29 0a>, source: <Buffer 63 6f 6e 73 6f 6c 65 2e 6c 6f 67 28 22 74 65 73 74 22 29 0a>, name: 'index.js', basename: 'index', ext: '.js', format: 'js', fs: [Object], path: '/Users/laskue/projects/test/patterns/atoms/button/index.js', pattern: [Object], meta: [Object], dependencies: {} } } }

Edit:
This could be the change that breaks patternplate https://github.com/nodejs/node/pull/5348

**Comment by marionebl** [comment]
Possibly related to https://github.com/defunctzombie/node-browser-resolve/pull/80 as browser-resolve is what is used in browserify after all. Anyway, the passed object appears to be an entire `pattern` object. That is clearly a bug.
