### ISSUE TITLE
import none default exports

### ISSUE THREAD

**Issue by nottobe** [sinnerschrader/patternplate#74]
When i have a dependency in my patternplate project package.json and i'm referencing a named export from my dependency in some of my pattern
`import list from 'other-package/list';`

This results into 2 dependencies in the package.json file in the distribution folder after commonjs build
`{
  "dependencies": {
    "other-package/list": "*",
    "other-package": "0.0.1"
  }
}`

**Comment by marionebl** [comment]
Thanks for reporting, I'll have a look into this.

**Comment by marionebl** [comment]
This requires changes to the following transforms:

* [x] [react](https://github.com/sinnerschrader/patternplate-transform-react)
* [ ] [resolve-imports](https://github.com/sinnerschrader/patternplate-transform-resolve-imports)
* [ ] [resolve-includes](https://github.com/sinnerschrader/patternplate-transform-resolve-includes)

**Comment by marionebl** [comment]
Turns out the specialized resolve transforms already used the first path fragment of require ids only. This should behave as expected now.
