### ISSUE TITLE
Cannot read property 'selfClosing' of undefined

### ISSUE THREAD

**Issue by MartinHelmut** [sinnerschrader/patternplate#75]
Hey, the following Problem occurred during a build after a clean install:

```shell
TypeError: Cannot read property 'selfClosing' of undefined
    at CodeGenerator.JSXElement (node_modules/babel-generator/lib/generators/jsx.js:66:11)
    at CodeGenerator._print (node_modules/babel-generator/lib/printer.js:184:17)
    // ...
```

related to "patternplate-console".

This is an example of the JSX code line used to reproduce the error:

```javascript
return (
    <hr className={className}/>
);
```

Seems like there was an update for `babel-generator` / `babel-types`, a patch version from `6.10.1` to `6.10.2`. Maybe the following change is related: https://github.com/babel/babel/commit/d7c0fbdf5b6c4fc0dd944408000ad8c7d9cdba96 ?

**Comment by marionebl** [comment]
Thanks for reporting, I'll investigate.

**Comment by marionebl** [comment]
@MartinHelmut  Can you still repdroduce this?

**Comment by MartinHelmut** [comment]
Unfortunately yes, the same error, nothing changes. My command for the test in a pp project:

```shell
rm -fr node_modules && npm cache clean && npm i
```

And then a build, fails again.

**Comment by marionebl** [comment]
According to my tests this happens with npm@3 only, pointing at some incompatibility issue with babel-generator.

**Comment by marionebl** [comment]
Ok... This is seriously weird.

node@4, npm@2 works before and after changes
node@5, npm@3 doesn't work before/after changes
node@6, npm@3 works after changes

**Comment by marionebl** [comment]
Seems to be connected with babel-template, investigating further.

**Comment by marionebl** [comment]
Fixed at at last. cc @Dangoo
