### ISSUE TITLE
Pure components: React required?

### ISSUE THREAD

**Issue by Dangoo** [sinnerschrader/patternplate#76]
When writing a stateless (or pure) component like this:

```javascript
const Component = (props) => {
    return (
        <div>{props.text}</div>
    );
}
```

returns the following error message:

```
> Error in "component" during transform "react-to-markup" of "
<UserPath\>/patterns/component/demo.jsx": Error during rendering of file
<UserPath\>/patterns/component/demo.jsx in pattern component: 
Tried to print offending lines React is not defined
[1m[31mfunction _interopRequireDefault(obj) { 
  return obj && obj.__esModule ? 
     obj : { "default": obj }; }
  [39m[22m var _Pattern = require('Pattern');
```

Importing React solves the problem, but why is it necessary here even though there is no React functionality here?

 ```javascript
import * as React from 'react';

const Component = (props) => <div>{props.text}</div>;
```

**Comment by marionebl** [comment]
`jsx` is desugared to `React.createElement` CallExpressions by `babel`, which `patternplate-transform-react` uses.

When the transformed code hits `patternplate-transform-react-to-markup` your examples roughly look like this:

```js
var Component = function Component(props) {
    return React.createElement(
        "div",
        null,
        props.text
    );
};
```

Which clearly lacks a binding for `React`.

---
See [babel-console](https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-1&experimental=true&loose=false&spec=false&code=const%20Component%20%3D%20(props)%20%3D%3E%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3Cdiv%3E%7Bprops.text%7D%3C%2Fdiv%3E%0A%20%20%20%20)%3B%0A%7D) for reference
