### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/patternplate#82]
For new features and changed semantics inbound with release `v1.0.0` new icons are needed:
- [x] "Source Code" for use in the collapsed bottom pattern toolbar
- [x] "Rulers" as action icon to toggle media-query display
- [x] "Keyboard key" as action icon to bring up the shortcut lightbox
- [x] "Issue" as action icon to bring up the issue lightbox
- [ ] "Exit" as inline icon for external links rendered into markdown
- [ ] "References" as action icon for a view that shows the connections between docs and patterns

---

Bonus points for constructing them via JS :trollface:

**Comment by Dangoo** [comment]
What do you mean by "contructing via JS"? 😁

**Comment by Dangoo** [comment]
@marionebl 
Wich icon style would you prefer for media queries:

#1 From PP-Icon set
![viewports-pp](https://cloud.githubusercontent.com/assets/1252204/18411794/7b076052-777f-11e6-820a-1d6ff4097824.png)

#2 From Google Design "flip"
![flip-google](https://cloud.githubusercontent.com/assets/1252204/18411827/5ea0a468-7780-11e6-9601-b2144a50ae15.png)

#3 From Google Design "Aspect Ratio"
![aspect-ratio-google](https://cloud.githubusercontent.com/assets/1252204/18411819/2403b61a-7780-11e6-94a1-c88b39266f17.png)

**Comment by marionebl** [comment]
Obsolete
