### ISSUE TITLE
0.15.16 - react-to-markup automount does not work after deploy

### ISSUE THREAD

**Issue by escapedcat** [sinnerschrader/patternplate#86]
Locally JavaScript is being loaded and executed when using this option:
```js
  "options": {
    "react-to-markup": {
      "opts": {
        "automount": true
      }
    }
  }
```

After a deploy (actually not sure how this is different from the local build) teh JavaScript doesn't work anymore. I get:
```
GET http://myurl.com/demo/molecules/undefined 
GET http://myurl.com/api/react-mount/molecules/my-module 404 (Not Found)
```

Let me know if you need further details.

**Comment by marionebl** [comment]
Thanks for reporting! I checked back with the project in question and verified this is fixed for patternplate@0.18. The earliest patternplate-server version containing the fixes in question is [0.16.4](https://github.com/sinnerschrader/patternplate-server/releases/tag/v0.16.4). I'd recommend to update to 0.18, so I opened a PR on the project 🚀.

Feel free to reopen if the problem persists.

## Relevant changes
* **undefined references** [sinnerschrader/patternplate-server#14f1df5](https://github.com/sinnerschrader/patternplate-server/commit/14f1df5636dc37a76f5a2ce26fbc73607bb09b7d)
* **missing component js** [sinnerschrader/patternplate-server#14f1df5](https://github.com/sinnerschrader/patternplate-server/commit/14f1df5636dc37a76f5a2ce26fbc73607bb09b7d)
