### ISSUE TITLE
Allow for multiple output formats per pattern

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/patternplate#99]
## Rationale

Currently patternplate does allow only one transform chain per given pattern format, e.g.:

``` js
// configuration/patternplate-server/patterns.js
{
  formats: {
    jsx: {
      name: 'JSXFormatName',
      transforms: ['react', 'react-to-markup']
    },
   // how to add additional transform chains for jsx here?
  }
}
```

This currently is a critical limitation of patternplate's transform system and prevents efficient usage of transforms that produce additional or non-critical artifacts, such as: auto-generated documentation, typescript typings, intermediary css-modules etc. 
## Features
- [ ] patternplate allows definition of multiple transform chains. The exact notation of configuration is up for debate inside this Github Issue.
- [ ] patternplate maintains backwards compatibility with current configuration `.patterns.formats`

**Comment by KnisterPeter** [comment]
I would start with add this optional configuration format:
``` js
// configuration/patternplate-server/patterns.js
{
  formats: {
    jsx: [{
      name: 'JSXFormatName',
      transforms: ['react', 'react-to-markup']
    }]
  }
}
```
The formats could be an error and contain multiple transform chains.
This does not make clear wich is the critical-path, but I think for a start we could asume that the first format transform chain is the most critical.

**Comment by marionebl** [comment]
Obsolete as patternplate will move towards a dev/design tool without own transform chain.
